name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependecies
        run: sudo apt install lcov

      - name: Coverage
        run: make clean coverage

      - name: Compile
        run: make clean compile
